wip

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -107,6 +107,9 @@ jobs:
         id: build
         # Want to run this regardless of the state of the previous step
         if: success() || failure()
+      # - name: Pass or fail
+      #   run: |
+      #     if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
       - run: |
           echo "Evaluate previous outcomes"
           echo $FOO
@@ -114,6 +117,8 @@ jobs:
           echo $BAR
           echo
           echo $BAZ
+          echo
+          echo $TOO
           exit 1;
         env:
           FOO: ${{ join(steps.*.outcome, ',') }}
